feat: UAVCAN_FWD_MBD
aviant-tech/PX4-Autopilot pull request #36
Opened 2023-10-04 07:19 UTC by oystub

Forward moving baseline data received via UAVCAN to all CAN buses.
This is useful for a GPS-for-yaw setup with receivers on different buses

Please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/) to align on pull requests if necessary. You can then open draft pull requests to get early feedback.

Previously, both receivers have to be on the same UAVCAN bus when using GPS-for-yaw. We want to use receivers on different CAN buses for redundancy reasons.

This PR adds a new parameter, "UAVCAN_FWD_MBD", which when enabled, subscribes to moving baseline data messages over UAVCAN. When a message is received, it is published to all UAVCAN buses.

Currently, the message is published to all UAVCAN buses, also the one from which it was received. A custom publisher could be implemented to avoid sending it here as well.

This has been tested using a GPS-for-yaw setup with two ARK RTK GPS modules, and a Cube Orange autopilot with one receiver plugged into each CAN bus.

2023-10-09 07:09 UTC, kibidev reviewed
Code looks good to me, but I am a bit worried that sending the message back to the originating interface may lead to unforeseen problems in the future.
How much effort would it be to write the custom publisher?

2023-10-31 12:47 UTC, oystub commented
I modified the code to

- Not broadcast on the originating interface
- Preserve the original source node id of the forwarded message

This required some changes to libuavcan, see https://github.com/aviant-tech/libuavcan/pull/1

2023-11-22 12:45 UTC, kibidev requested changes
Before merge:
- Squash commits and use repo style for commit message (e.g. "uavcan: forward etc etc")
- Move submodule update to separate commit
- Check if we can get submodule changed merged upstream
- Need test flights evaluated

2023-11-22 12:45 UTC, kibidev commented on src/drivers/uavcan/sensors/gnss.cpp
> +	res = _sub_moving_baseline_data.start(MovingBaselineDataBinder(this, &UavcanGnssBridge::moving_baseline_sub_cb));
Do you need to start this if UAVCAN_FWD_MBD is disabled?

2023-12-01 16:54 UTC, oystub commented
Implemented suggested changes and rebased.

TODO:
- Try to get libuavcan and this upstream.
- More flight tests

2023-12-07 10:11 UTC, oystub commented
Closing this PR, as these changes are incorporated into a common branch for all rtk yaw fixes:
https://github.com/aviant-tech/PX4-Autopilot/tree/aviant/gps-rtk-yaw

2023-12-07 10:11 UTC, closed without merging